# Generated by Django 4.1.9 on 2023-07-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='interactions',
        ),
    ]
