# Generated by Django 4.1.9 on 2023-07-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParanormalInfo',
            new_name='Info',
        ),
    ]
