# Generated by Django 4.2.3 on 2023-07-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_form_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='activityDescription',
        ),
        migrations.RemoveField(
            model_name='form',
            name='address',
        ),
        migrations.RemoveField(
            model_name='form',
            name='experiencedActivity',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phoneNumber',
        ),
    ]
