# Generated by Django 4.1.9 on 2023-07-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_paranormalinfo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(default='address', max_length=150),
        ),
        migrations.AddField(
            model_name='info',
            name='investigation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='street_address',
            field=models.CharField(default='address', max_length=250),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
