# Generated by Django 4.1.9 on 2023-07-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_info_email_info_investigation_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(default='email', max_length=150),
        ),
    ]
