# Generated by Django 4.1.9 on 2023-07-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_form_activitydescription_remove_form_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParanormalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('investigation_requested', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
